### ISSUE TITLE
App crash by install

### ISSUE THREAD

**Issue by ghost** [martijnpoppen/com.synology.ss#1]
The app immediately indicates after installation that the app has been closed due to a crash.!
![IMG_7243](https://user-images.githubusercontent.com/60585365/74196739-259e7580-4c5e-11ea-94b2-2807d524ccea.PNG)

DSM 6.2.2-24922 Update 4
Surveillance Station 8.2.6-6009
Homey 3.2.1
app 3.2.0.441

**Comment by marcschut002** [comment]
Hi @boboosterhof . I have pushed a new version 1.0.2 to the Appstore that might fix this problem.

**Comment by marcschut002** [comment]
Hi @boboosterhof, did 1.0.2 resolve the issue?

**Comment by ghost** [comment]
Sorry for the late response! It works, thanks!
