### ISSUE TITLE
Adding camera successfull, but no action rules for motion in syn nas

### ISSUE THREAD

**Issue by Sen-Sai** [martijnpoppen/com.synology.ss#11]
Diagnostic code : d88b6e9c-8420-4cc1-a8d5-cc0845a7d411

Version : 3.0.1
NAS DSM version :  6.2.3-25426 Update 3
Surv. version : 8.2.8-6335
Home 5.0

Synology NAS adding adds two action rules for home on/off, but adding camera does not add any action rules.

**Comment by marcschut002** [comment]
Hi @Sen-Sai, do you have motion detection enabled in the camera/device settings?
If so, please disable the setting, save the settings and then enable it again (and save the settings). This will trigger the creation of the motion detection rules for the camera on the NAS.

**Comment by Sen-Sai** [comment]
Thanks for the suggestion, but it doesn't work. Motion detection is set to be done by Surveillance station, not the camera itself as it can't, but from what I've read that should work. So I've turned it off and on again. No rules were made, also removed from Homey and re-added the camera made no difference.

**Comment by marcschut002** [comment]
That should work indeed, but did you check the settings on the NAS or on the Homey?
Maybe this topic will help? https://community.athom.com/t/app-surveillance-station-2/32737/38?u=bookmarc

**Comment by Sen-Sai** [comment]
I checked the setting on the NAS. So disabled camera motion detection in NAS, turned them on again. No new rules.
I create a flow in Homey on camera motion detection, but it is never triggered as there are no rules on the NAS.
I'll check your link now.

So yes.. Motion detection is "Actief" in de advanced settings of the camera in the Homey app. And no, no motion rules for the camera when switching off/on in NAS.
When first adding the NAS in homey I got a whitescreen.
I will remove the camera and the NAS from Homey. Then add them again. See if that works.

**Comment by Sen-Sai** [comment]
No same issue unfortunately.

**Comment by marcschut002** [comment]
Strange thing. I am working on a new release that validates the action rules and if they are not there it will add them to the NAS. When I am finished with the test release I will let you know.

**Comment by Sen-Sai** [comment]
New version seems to have fixed this! Many thanks!
