### ISSUE TITLE
Error message "... is not in the cert's list"

### ISSUE THREAD

**Issue by mostlyflawles** [martijnpoppen/com.synology.ss#12]
I get this error message when I try to add a Surveillance Station.

"request to https://192.168.1.1:5001/webapi/auth.cgi failed, reason: Hostname/IP does not match certificate's altnames: IP: 192.168.1.1 is not in the cert's list"

Please advise what could be wrong.

**Comment by mostlyflawles** [comment]
Get this message if I use the synology.me address.
request to https://X.synology.me:5001/webapi/auth.cgi failed, reason: connect ECONNREFUSED 111.1.1.1:5001

**Comment by marcschut002** [comment]
Hi @mostlyflawles , Certificates only work on hostnames and not with local ip addresses. With an ipaddress you can only connect if you select http iso https.

Your second message probably has to do with some firewall rules in your router that blocks port 5001 or does not forward that port to your NAS.

**Comment by mostlyflawles** [comment]
I went for http on port 5000, didn't think http was an option on my NAS. Thanks!

**Comment by marcschut002** [comment]
Thanks for the reply, enjoy the app! I will close this issue.
