### ISSUE TITLE
request to https

### ISSUE THREAD

**Issue by felho001** [martijnpoppen/com.synology.ss#13]
When i try to add synology first in app settings auth failed reason connect econnrefused. How can fix this if I use synology DScam app work same user and password and no have this user 2 fakt auth. I changed the port standerd 5001 and after say this.

![synology](https://user-images.githubusercontent.com/45117257/115673564-12506500-a34d-11eb-9f19-96fb3e26e83d.jpg)
how fix this? thanks

**Comment by marcschut002** [comment]
Hi @felho001, the error says that there is a problem with the certificate on that domain. The Homey app validates (default for Homey) the certificate.
I think the DScam App does not validate the certificate when connecting to your DS. It is a setting at the login page in the DSCam app (bottom left). That might explain the different results.

**Comment by felho001** [comment]
and how can fix this. Synology surveillance station use synology cert that is set on synology nas. Hat can I do?

**Comment by marcschut002** [comment]
https://www.synology.com/en-global/knowledgebase/DSM/help/DSM/AdminCenter/connection_certificate 
I use the Let's Encrypt method described in the manual.

**Comment by felho001** [comment]
ok thanks i will try

**Comment by felho001** [comment]
now works thanks for help

**Comment by marcschut002** [comment]
Great! Enjoy the app!
