### ISSUE TITLE
Snapshot Option for Flows

### ISSUE THREAD

**Issue by Jansrt** [martijnpoppen/com.synology.ss#14]
Hi Marc,
I would like to ask a quick question.
On the Homey website, a snapshot function is mentioned for this app.
I can see a snapshot clicking on the camera (device icon).
However, I do not see an option to select making a snapshot while making a flow. 
Should this be an option? If not; I would like to have it as an option.
Best,
Rob

**Comment by marcschut002** [comment]
Hi @Jansrt , I will take a look at it!

**Comment by marcschut002** [comment]
If you need the snapshot in a flow you can use the snapshot tag that is available.

![Screenshot 2021-07-06_19-00-49-982](https://user-images.githubusercontent.com/38959867/124639596-a4680400-de8c-11eb-99ec-c7edb96680f0.png)

**Comment by Jansrt** [comment]
Thank you for your quick answer! I have implemented the necessary changes successfully.

**Comment by A333333** [comment]
In my case I can make a snapshot but seems not be available. I can only select pictures from 'gallery'. I am
Struggling with it for months.
Am I missing something?![image](https://user-images.githubusercontent.com/41258710/132473291-2aa00e5c-dadc-45ab-8d48-290619cca0e2.jpeg)

Adri

**Comment by marcschut002** [comment]
Hi @A333333 ,
I don't think you have selected the right push notification action card.  You should select the one with "tag" on it.
![Screenshot 2021-09-09_15-34-53-317](https://user-images.githubusercontent.com/38959867/132696269-339426cb-54a1-4ad7-a741-be67ba4e652c.png)

**Comment by A333333** [comment]
Hi Marc,

There is no other way to select. It was working, suddenly the tag field was missing.
![image](https://user-images.githubusercontent.com/41258710/132883837-5e32acce-f1f9-4a0d-aba4-d6b1d8823041.jpeg)
![image](https://user-images.githubusercontent.com/41258710/132883876-d9b29527-4284-4c2b-8876-4ddd34f6890f.jpeg)
![image](https://user-images.githubusercontent.com/41258710/132883896-2c96754f-7a6b-4364-a52c-7865c9f51067.jpeg)
![image](https://user-images.githubusercontent.com/41258710/132883916-59146fac-edc1-4196-beb5-6b2d80f73b66.jpeg)

This is what I can select.

This was a working flow card:

![image](https://user-images.githubusercontent.com/41258710/132884443-29a29e28-3fc9-47ba-8ba7-f0c3c64ab791.jpeg)

Strange...

**Comment by A333333** [comment]
Hi,

After last update of your app, the tag was working again.

Grtz, Adri

Van: marcschut002 ***@***.***>
Verzonden: donderdag 9 september 2021 15:39
Aan: marcschut002/athom.com.synology.ss ***@***.***>
CC: Adri Huizing ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [marcschut002/athom.com.synology.ss] Snapshot Option for Flows (#14)


Hi @A333333<https://github.com/A333333> ,
I don't think you have selected the right push notification action card. You should select the one with "tag" on it.
[Screenshot 2021-09-09_15-34-53-317]<https://user-images.githubusercontent.com/38959867/132696269-339426cb-54a1-4ad7-a741-be67ba4e652c.png>
