### ISSUE TITLE
Login problem

### ISSUE THREAD

**Issue by Thijzelt** [martijnpoppen/com.synology.ss#15]
Hallo,

Allereerst bedankt voor het maken van deze app👌 waardering voor de tijd en energie die je erin gestoken hebt.

Ik krijg helaas het niet werkend en waarschijnlijk doe ik iets verkeerd. Als ik de synology probeer aan te melden dan geeft ie een melding.  De user en password zouden goed moeten zijn, en ik heb het ook geprobeerd door een andere port in te instellen op de nas alleen voor surveillance station. Kan het zijn dat mijn nas te oud is ds112?

Alvast bedankt 

Groeten thijs

![IMG_20210731_175722](https://user-images.githubusercontent.com/72579527/127745814-ea2d92fc-d402-45cc-b9b3-74faf16afa89.png)

**Comment by marcschut002** [comment]
Ik kan niet goed zien welke poort je hebt gebruikt, maar voor http zou dat standaard 5000 moeten zijn. Heb je die ook geprobeerd?

**Comment by Thijzelt** [comment]
Ik had de port gewijzigd op de nas naar 9900 voor http omdat 5000 niet werkte.
Maar ik heb alles teruggezet alleen helaas zonder resultaat, heb geen firewall aanstaan dus daar kan het aan liggen 

Kunnen het andere instellingen zijn? Heb een gebruiker áangemaakt, helaas zonder resultaat

**Comment by marcschut002** [comment]
Heb je het ook met een admin gebruiker geprobeerd? De gebruiker die je aanmaakt zal in ieder geval in de groep administrators moeten zitten anders kunnen de juiste instellingen niet gemaakt worden vanuit Homey om goed te kunnen samenwerken met de Surveillance Station / Synology.

**Comment by marcschut002** [comment]
welke versie van DSM en Surveillance Station heb je draaien?

**Comment by Thijzelt** [comment]
De versie van surveillance station is 
8.2.9-6459

DSM 
6.2.4-25556

Ik heb de gebruiker gecontroleerd en staat in administrors, ik kan ook inloggen bij surveillance station met deze gegegens. Ik heb geprobeerd de port te wijzigen op om die rechtstreeks te benaderen helaas zonder succes via de homey
Zijn er misschien nog tips om te proberen?

**Comment by marcschut002** [comment]
De versies zouden volgens mij geen punt moeten zijn. Dit zijn voor versie 7 DSM de meest recente versies en ik heb niets aangepast om het werkend te krijgen op versie 7. Zit je Homey (met wifi verbinding) wel in hetzelfde netwerk als je Synology (bekabeld) ?
