### ISSUE TITLE
Cannot set HomeMode on or off from a flow

### ISSUE THREAD

**Issue by Hulliee** [martijnpoppen/com.synology.ss#16]
Hi,
I'm having trouble setting HomeMode On or Off from a Honey flow:
`cannot read property 'setHomeMode' of undefined`
Directly in the app it works.
I'm connected from Homey to my Synology with an admin user and I'm using DSM7.01

**Comment by marcschut002** [comment]
Hi @Hulliee , you are right. This is a bug. I will fix this asap.

**Comment by marcschut002** [comment]
You can try the new version (4.0.4) with a fix for the home mode action card.
https://homey.app/nl-nl/app/com.synology.ss/Surveillance-Station-2/test/

**Comment by Hulliee** [comment]
@marcschut002 Yes, this version is working! Good one!

**Comment by Hulliee** [comment]
@marcschut002 A "beer" is on it's way! ;-)

**Comment by marcschut002** [comment]
@Hulliee, I appreciate it! Thanks for the beer!
