### ISSUE TITLE
No Connection

### ISSUE THREAD

**Issue by HQOFIQ** [martijnpoppen/com.synology.ss#17]
Hi,
got my brandnew Homey Pro yesterday and installed all various devices - only one I wasn't able to connect to is my Synology Surveillance Station, trying both the Surveillance Station and Surveillance Station 2 App from Homey. Since my Surveillance Station is working fine and is reachable from within and outside my home via web/smartphone I am not able to see where the problem is located. Using my "yourname.synology.me" (where yourname is my Synology-ID) doesn't work (Timeout) but I can connect by any other means to it no matter what ...

**Comment by marcschut002** [comment]
It is hard to tell from a distance, but most of the time a timeout means that the Homey could not connect to the hostname and port you provided. Maybe a firewall thing. Does it work when you fill in the LAN IP address and port number + http (iso https) ?

**Comment by HQOFIQ** [comment]
Hi - using the LAN IP gives back this:
"invalid json response body at http://x.x.x.x:5001/webapi/auth.cgi reason: Unexpected token < in JSON at positon 0" (where x.x.x.x is my IP that I deleted from the statement)
(used http not https)
PS: Thanks for the quick response!

**Comment by marcschut002** [comment]
Could you try port 5000 iso 5001? (5000 is for http, 5001 is https) . And what version of Homey, this app and surveillance station do you have?

**Comment by HQOFIQ** [comment]
Tried port 5000, no connection for my Homey Pro (2.0)
"Failed to connect, please make sure the settings are correct"

Versions:
Homey Pro (early 2019): 7.2.0
Homey App (Android 10): 6.9.3.827 
and Homey Web App (Windows 11): no Version mentioned 
Surveillance Station 2: 4.0.4
Synology Surveillance Station: 8.2.10-7310
DSM: 7.0-41890

**Comment by marcschut002** [comment]
Versions are oké so that is not the problem. Your Homey is connected over wifi . Are you sure that the Homey can reach the NAS or any other device in your local network?

**Comment by HQOFIQ** [comment]
Yes, everything added without a problem on WiFi and I can also login to my Synology NAS and Surveillance Station eezy peezy ...

**Comment by marcschut002** [comment]
I am sorry but I am running out of options.. Maybe someone else has an idea what it could be?

**Comment by konradhuebner** [comment]
@HQOFIQ I just added this app to my Homey as well and it does work. My ideas, as I saw the error when trying HTTP over the HTTPS port and vice versa:
* please check if you have selected HTTP or HTTPS at the top. 
* For port 5000 you MUST select HTTP
* For port 5001 you MUST select HTTPS and have a valid certificate

**Comment by HQOFIQ** [comment]
@konradhuebner can you please tell me if you connect via a "YOURNAME.synology.me" or an IP address? And if you use the ...synology.me - does this work in the browser as a standalone link as well? because it doesnt for me ...

**Comment by konradhuebner** [comment]
@HQOFIQ I connect through the IP address inside my local network. Works in the browser as well like this. As Homey executes everything locally, you can use this variant without issues.

**Comment by anderhau2** [comment]
I have a similar problem. Cannot connect and I'm getting "Could not get Surveillance Station info".

I'm using HTTP, port 5000 and IP for my Synology Box. Have tried the other "Synology Surveillance Station" app for Homey and it connects and find my cameras, but it wont push snapshots in my flows. So I wanted to give this app a try.

**Comment by HQOFIQ** [comment]
@marcschut002 I was finally able to connect but only by using my wifes synology account (which has access to the surveillance station but not as admin just as a user) - works so far. The only difference to my account is, that she has no 2FA active with her synology account - so you might want to look into that, seems to be the problem for connecting because hers worked instantly with your app!

**Comment by konradhuebner** [comment]
@HQOFIQ this is no real surprise, as the plugin will have hard times to get a proper and in-time 2FA authorization whenever it might restart. Maybe you create an account with no remote login rights, that is only used for surveillance station, and use that within Homey?

**Comment by marcschut002** [comment]
@HQOFIQ 2FA should not be a problem, if you provide credentials for your account with the app and your account has 2FA enabled, you get another form to fill in your code. With valid credentials and 2FA the app receives 2 codes from the Synology to keep communicating even when the Synology or Homey reboots. There should be something else with your account that prevents te app to get a proper connection.

**Comment by mtudor** [comment]
I had the same issue as @HQOFIQ, with the same error message "Unexpected token <".  For me, I was connecting to a Surveillance Station with a hostname that was in the subject alternative name but NOT the main subject name.  When I changed the hostname to the one in the main subject name, everything worked as expected.

For example, a certificate with:

Subject Name: CN=my.host.com
SAN: DNS Name=my.othername.host.com
         DNS Name=my.host.com

I see the error about the unexpected token if I enter my.othername.host.com as the hostname in the Surveillance Station 2 Homey app but everything works as expected if I use my.host.com.

**Comment by bckp** [comment]
I belive you must connect to the Survilliance station, not DSM itself, so port is 9900 or 9901 by default...

BTW: So far, from my tests, it is best to use separate account for homey, without 2FA and restricted login just for homey local IP address, that way im safe that nobody else can login on that account only homey can.
