### ISSUE TITLE
Motion detection not working

### ISSUE THREAD

**Issue by Marc1979** [martijnpoppen/com.synology.ss#2]
Hello, great app btw.
Have installed it since last week, but don't get the motion detection working. If I enable it in the app I get an error " no rule found". If i login onto the dsm dashboard of surveillance station then I see the tasks in the task manager. Further everything else is working well. Already restarted the app, homey and the NAS

**Comment by marcschut002** [comment]
Hi @Marc1979, thank you for your feedback. Could you give me some more details about Homey version, DSM version and Surveillance Station version? Could you also look at the endpoint (url) for the action in the taskmanager? (edit task and go to the action tab). Does that url make sense? It should point to your Homey's local address.

**Comment by marcschut002** [comment]
@Marc1979 , I have found the problem en put a fix in version 1.0.1. Please remove all tasks after the update and try to disable/enable the motion detection on the camera in Homey.

**Comment by Marc1979** [comment]
Ok, thanks!
Was just typing a message to you about the software version of the NAS and Homey, but will try the new version.. (was at work, so could not answer earlier)

**Comment by Marc1979** [comment]
Have installed the new version thru CLI, can comfirm that it is working now. 
Is it possible to change/add the class of device so you will get an exclamation mark in the card of the homey APP when there is a movement (now you only see that the zone is getting active)

**Comment by marcschut002** [comment]
@Marc1979 great! I will take a look at the exclamation mark. Looks like a nice feature.

**Comment by marcschut002** [comment]
I will close this issue as the original issue is resolved.
