### ISSUE TITLE
Snapshot no longer available in flow

### ISSUE THREAD

**Issue by Wouter-Berman** [martijnpoppen/com.synology.ss#20]
Hi Marc,
Previously (I don't know which version) it was possible to trigger a snapshot in a flow and send the resulting image as a push notification. In the current version the snapshot action creates a snapshot in Surveillance Station but the resulting image is no longer available as tag in the flow. Therefore, it is no longer possible to sent the image in a push notification. I used this feature for when the door bell was pressed.
I would really appreciate if this feature could be restored.
Regards,
Wouter

**Comment by marcschut002** [comment]
Hi @Wouter-Berman , I would have to look into that. The tag should allways be available.

**Comment by Wouter-Berman** [comment]
I am using this scenario:
![image](https://user-images.githubusercontent.com/73526294/166907048-036b45b0-29d1-4f7a-9c97-7f57440666e0.png)
And when I try to select the image for the push notification I can only select the album cover of my Sonos appliance:
![image](https://user-images.githubusercontent.com/73526294/166907338-c801e7ec-e8e3-4a1e-b863-2f3b4c960c8e.png)

**Comment by Wouter-Berman** [comment]
Hi Marc,
The issue is solved. Restarting the app made the snapshot available in the flow again.
I am sorry for bothering you with this.
Kind regards,
Wouter Berman
