### ISSUE TITLE
Disable/enable camera 

### ISSUE THREAD

**Issue by mostlyflawles** [martijnpoppen/com.synology.ss#21]
Disable camera flow does not work me, the cameras is not disbled. I can disable the camera in the Surveillance app without any problem.

Any idea ideas how to troubleshoot?

**Comment by mostlyflawles** [comment]
It works to enable and disable the devices in this Homey app manually. But regardless if it's disabled or not the device is enabled is Synology surveillance station 2.
And as stated above, having Disable/enable camera in a flow does not have any impact on the status of the device.

**Comment by marcschut002** [comment]
Hi @mostlyflawles , thank you for the report. This should work,  will try to fix this.

**Comment by marcschut002** [comment]
@mostlyflawles could you please reboot the homey app and check if this works?

**Comment by mostlyflawles** [comment]
Did now and reboot did not solve issue with 'flow'.
I've tried disable one camera in the Synology desktop app and that camera in Homey turns up as 'disabled'.
But still, a camera which is manually disabled in Homey app is still enabled in SSS.

**Comment by marcschut002** [comment]
I have tested it with my own setup and have no problem with the flow. Is this the only action that is not working with the camera?

**Comment by mostlyflawles** [comment]
I 've been having issues with the connection between this app and NAS, I fixed it today and had to switch to local ip and http. Now the enable/disable function works for me.
I can't recall exactly what setup I was on before when it didn't work.

So, if in trouble, goto local ip and http. I guess. =)
