### ISSUE TITLE
Status of home mode not reported correctly

### ISSUE THREAD

**Issue by mostlyflawles** [martijnpoppen/com.synology.ss#22]
This test flow does not report correct status of home mode.
![image](https://user-images.githubusercontent.com/25802524/178145516-6aad8a14-7b59-4ec2-bda3-57f17f9698ec.png)

If I open Surveillance Station device and change home mode, the status is reported correct.
But If I change home mode in Surveillance Station Windows Client or with a flow, the status is not reported correctly.
![image](https://user-images.githubusercontent.com/25802524/178145649-bdddd672-b05a-4218-8f3a-323932fa7a31.png)
In the Surveillance Station Windows Client I can see that my enable/disable-home-mode-flows are working fine.

**Comment by mostlyflawles** [comment]
Nobody else having issue with home mode?

**Comment by bckp** [comment]
Same for me... I will try to figure out what is wrong and how to fix this and send MR

**Comment by bckp** [comment]
Hmmm, so update, i repair actions and now state changes correctly
