### ISSUE TITLE
Cannot connect Synology NAS or camera's since Homey's update t0 8.1.0

### ISSUE THREAD

**Issue by Jansrt** [martijnpoppen/com.synology.ss#23]
The app has worked perfectly for many years, but I cannot connect Synology NAS or camera's since Homey's update to 8.1.0. I have tried all different kinds of things, but nothing does fix it.

**Comment by martijnpoppen** [comment]
Hey,
Please send a diagnostic report to me otherwise I can't help you ;)

**Comment by Jansrt** [comment]
Thanks for your quick response.

This is the code:fd34f335-30f1-43f8-b627-de6c92bff78c.

Rob T.A. Janssen

Tel.: +31 79 360 02 11
Mobile.: +31 6 54 70 88 65


Van: Martijn Poppen ***@***.***>
Datum: woensdag, 23 november 2022 om 21:40
Aan: martijnpoppen/com.synology.ss ***@***.***>
CC: Rob T.A. Janssen ***@***.***>, Author ***@***.***>
Onderwerp: Re: [martijnpoppen/com.synology.ss] Cannot connect Synology NAS or camera's since Homey's update t0 8.1.0 (Issue #23)

Hey,
Please send a diagnostic report to me otherwise I can't help you ;)

**Comment by martijnpoppen** [comment]
Hey,
Ik zie wel wat error. Heb je al geprobeerd de app te herstarten?

**Comment by Jansrt** [comment]
Meerdere keren. Alle apparaten ook verwijderd en opnieuw proberen te installeren. Homey ook meerdere keren herstart. Alle andere apps werken wel.


Rob T.A. Janssen

Tel.: +31 79 360 02 11
Mobile.: +31 6 54 70 88 65


Van: Martijn Poppen ***@***.***>
Datum: woensdag, 23 november 2022 om 21:51
Aan: martijnpoppen/com.synology.ss ***@***.***>
CC: Rob T.A. Janssen ***@***.***>, Author ***@***.***>
Onderwerp: Re: [martijnpoppen/com.synology.ss] Cannot connect Synology NAS or camera's since Homey's update t0 8.1.0 (Issue #23)

Hey,
Ik zie wel wat error. Heb je al geprobeerd de app te herstarten?

**Comment by martijnpoppen** [comment]
Voor zover ik kan zien is er of een probleem dat je een cloud connectie wilt maken of je logingegevens zijn niet juist.

Ik zie timeouts op je url namelijk

**Comment by Jansrt** [comment]
De inloggegevens kloppen, maar ik krijg inderdaad geregeld time-outs. Ik heb zowel via lokaal IP-adres proberen in te loggen, als via een cloud-adres. Het maakte niet uit of ik daarbij de instelling cloud-adres / lokaal adres koos. Kun je hier iets mee?

Ik heb een gigabit ethernetverbinding binnen en naar buiten. WiFi is ook meer dan snel genoeg. Geen issues met ander IT in huis.


Rob T.A. Janssen

Tel.: +31 79 360 02 11
Mobile.: +31 6 54 70 88 65


Van: Martijn Poppen ***@***.***>
Datum: woensdag, 23 november 2022 om 22:13
Aan: martijnpoppen/com.synology.ss ***@***.***>
CC: Rob T.A. Janssen ***@***.***>, Author ***@***.***>
Onderwerp: Re: [martijnpoppen/com.synology.ss] Cannot connect Synology NAS or camera's since Homey's update t0 8.1.0 (Issue #23)

Voor zover ik kan zien is er of een probleem dat je een cloud connectie wilt maken of je logingegevens zijn niet juist.

Ik zie timeouts op je url namelijk

**Comment by martijnpoppen** [comment]
Enige wat ik kan zien is dat je login niet geaccepteerd wordt door de app.

Klopt de port wel? 5001 is meestal de port van de DSM en niet van Surveillance Station

**Comment by Jansrt** [comment]
Ik log in met mijn admin account dat overal bij kan. En het heeft altijd goed gewerkt zo.

Inloggen met mijn Surveillance account via dezelfde poort werkt ook niet.

De standaard poorten voor Surveillance Station van Synology zijn ook 5000 en 5001.

Het heeft altijd gewerkt, waarom nu niet meer?


Rob T.A. Janssen

Tel.: +31 79 360 02 11
Mobile.: +31 6 54 70 88 65


Van: Martijn Poppen ***@***.***>
Datum: woensdag, 23 november 2022 om 22:50
Aan: martijnpoppen/com.synology.ss ***@***.***>
CC: Rob T.A. Janssen ***@***.***>, Author ***@***.***>
Onderwerp: Re: [martijnpoppen/com.synology.ss] Cannot connect Synology NAS or camera's since Homey's update t0 8.1.0 (Issue #23)

Nee hier kan ik niet veel mee :P

Enige wat ik kan zien is dat je login niet geaccepteerd wordt door de app.

Klopt de port wel? 5001 is meestal de port van de DSM en niet van Surveillance Station

**Comment by martijnpoppen** [comment]
Dat kan ik helaas niet verklaren waarom het nu niet werkt.
Enige wat ik zie is dat je url niet geaccepteerd wordt. 

Er zijn geen aanpassingen geweest in de Homey app.

Zou je een herstart kunnen doen en dan een nieuw diagnostisch rapport sturen?

**Comment by Jansrt** [comment]
Een aantal weken geleden had ik het probleem ook, maar toen was het een onvolledige update van Homey. Opgelost toen met Athom.

Nu update gecontroleerd.

Herstart van de app of Homey?


Rob T.A. Janssen

Tel.: +31 79 360 02 11
Mobile.: +31 6 54 70 88 65


Van: Martijn Poppen ***@***.***>
Datum: woensdag, 23 november 2022 om 23:13
Aan: martijnpoppen/com.synology.ss ***@***.***>
CC: Rob T.A. Janssen ***@***.***>, Author ***@***.***>
Onderwerp: Re: [martijnpoppen/com.synology.ss] Cannot connect Synology NAS or camera's since Homey's update t0 8.1.0 (Issue #23)

Dat kan ik helaas niet verklaren waarom het nu niet werkt.
Enige wat ik zie is dat je url niet geaccepteerd wordt.

Er zijn geen aanpassingen geweest in de Homey app.

Zou je een herstart kunnen doen en dan een nieuw diagnostisch rapport sturen?

**Comment by martijnpoppen** [comment]
Herstart van de app zou voldoende moeten zijn

**Comment by Jansrt** [comment]
Nieuwe code: c1f73bae-0610-4f73-8854-b8656df25768.

Dank!


________________

Rob T.A. Janssen
Mobile: +31 6 54 70 88 65

Sent from my mobile device.

Op 23 nov. 2022 om 23:24 heeft Martijn Poppen ***@***.***> het volgende geschreven:

﻿

Herstart van de app zou voldoende moeten zijn

**Comment by martijnpoppen** [comment]
Thanks,
Ik zie dat je inderdaad geen apparaat meer erin hebt staan.
zou je kunnen proberen om de surveillance station toe te voegen en daarna een nieuw rapport sturen?

Dan kan ik zien wat er tijdens dat process gebeurt. 😄

**Comment by Jansrt** [comment]
a2a0390f-067e-4028-9871-bb3f6acd04de. Sorry.


________________

Rob T.A. Janssen
Mobile: +31 6 54 70 88 65

Sent from my mobile device.

Op 23 nov. 2022 om 23:36 heeft Martijn Poppen ***@***.***> het volgende geschreven:

﻿

Thanks,
Ik zie dat je inderdaad geen apparaat meer erin hebt staan.
zou je kunnen proberen om de surveillance station toe te voegen en daarna een nieuw rapport sturen?

Dan kan ik zien wat er tijdens dat process gebeurt. 😄

**Comment by martijnpoppen** [comment]
Lijkt erop dat het gedeeltelijk werkt.

Kan je eens proberen een lokale connectie te maken. (192.168.178.4) op port: 5000 en protocol: http

**Comment by Jansrt** [comment]
Heb ik eerder vele keren geprobeerd. Dan krijg ik een foutmelding dat het adres niet in een bepaalde vrijstellingslijst voorkomt. Is dat genoeg?


________________

Rob T.A. Janssen
Mobile: +31 6 54 70 88 65

Sent from my mobile device.

Op 23 nov. 2022 om 23:51 heeft Martijn Poppen ***@***.***> het volgende geschreven:

﻿

Lijkt erop dat het gedeeltelijk werkt.

Kan je eens proberen een lokale connectie te maken. (192.168.178.4) op port: 5000 en protocol: http

**Comment by Jansrt** [comment]
Sorry http recentelijk nog niet getest. Ga ik nu doen.


________________

Rob T.A. Janssen
Mobile: +31 6 54 70 88 65

Sent from my mobile device.

Op 23 nov. 2022 om 23:51 heeft Martijn Poppen ***@***.***> het volgende geschreven:

﻿

Lijkt erop dat het gedeeltelijk werkt.

Kan je eens proberen een lokale connectie te maken. (192.168.178.4) op port: 5000 en protocol: http

**Comment by Jansrt** [comment]
Op die manier kan ik de NAS en de camera’s wel installeren. Ik ga morgen verder testen. OK? Dank!


________________

Rob T.A. Janssen
Mobile: +31 6 54 70 88 65

Sent from my mobile device.

Op 23 nov. 2022 om 23:51 heeft Martijn Poppen ***@***.***> het volgende geschreven:

﻿

Lijkt erop dat het gedeeltelijk werkt.

Kan je eens proberen een lokale connectie te maken. (192.168.178.4) op port: 5000 en protocol: http

**Comment by martijnpoppen** [comment]
Helemaal goed! :)

**Comment by Jansrt** [comment]
Een voor de zekerheid; de app staat nu het werkt nog wel op cloud url. Misschien dat dat tot (extra) verwarring bij het uitzoeken leidt.

Nogmaals dank!

Rob


Rob T.A. Janssen

Tel.: +31 79 360 02 11
Mobile.: +31 6 54 70 88 65


Van: Rob T.A. Janssen ***@***.***>
Datum: donderdag, 24 november 2022 om 00:13
Aan: martijnpoppen/com.synology.ss ***@***.***>
CC: martijnpoppen/com.synology.ss ***@***.***>, Author ***@***.***>
Onderwerp: Re: [martijnpoppen/com.synology.ss] Cannot connect Synology NAS or camera's since Homey's update t0 8.1.0 (Issue #23)
Op die manier kan ik de NAS en de camera’s wel installeren. Ik ga morgen verder testen. OK? Dank!

________________

Rob T.A. Janssen
Mobile: +31 6 54 70 88 65

Sent from my mobile device.

Op 23 nov. 2022 om 23:51 heeft Martijn Poppen ***@***.***> het volgende geschreven:
﻿

Lijkt erop dat het gedeeltelijk werkt.

Kan je eens proberen een lokale connectie te maken. (192.168.178.4) op port: 5000 en protocol: http

**Comment by martijnpoppen** [comment]
Hey,
Even ter check lukte het met port 5000 en http wel?

**Comment by Jansrt** [comment]
Ja en het werkt vandaag nog steeds zonder problemen. Ik werd er gisteren voor deze oplossing een paar keer uitgegooid.

Het blijft vreemd dat het jarenlang wel gewerkt heeft.

Zou het t.z.t. wel weer via een beveiligde verbinding kunnen?


Rob T.A. Janssen

Tel.: +31 79 360 02 11
Mobile.: +31 6 54 70 88 65


Van: Martijn Poppen ***@***.***>
Datum: donderdag, 24 november 2022 om 11:06
Aan: martijnpoppen/com.synology.ss ***@***.***>
CC: Rob T.A. Janssen ***@***.***>, Author ***@***.***>
Onderwerp: Re: [martijnpoppen/com.synology.ss] Cannot connect Synology NAS or camera's since Homey's update t0 8.1.0 (Issue #23)

Hey,
Even ter check lukte het met port 5000 en http wel?

**Comment by martijnpoppen** [comment]
Voor zover ik zie denk ik dat het door het certificaat komt. Ik zal een optie toevoegen in de app om SSL certificaat errors te negeren

**Comment by Jansrt** [comment]
Super!


Rob T.A. Janssen

Tel.: +31 79 360 02 11
Mobile.: +31 6 54 70 88 65


Van: Martijn Poppen ***@***.***>
Datum: donderdag, 24 november 2022 om 13:58
Aan: martijnpoppen/com.synology.ss ***@***.***>
CC: Rob T.A. Janssen ***@***.***>, Author ***@***.***>
Onderwerp: Re: [martijnpoppen/com.synology.ss] Cannot connect Synology NAS or camera's since Homey's update t0 8.1.0 (Issue #23)

Voor zover ik zie denk ik dat het door het certificaat komt. Ik zal een optie toevoegen in de app om SSL certificaat errors te negeren
