### ISSUE TITLE
Certificaat

### ISSUE THREAD

**Issue by wesllleyyy** [martijnpoppen/com.synology.ss#3]
Hallo.

Ik heb alles geprobeerd en gezocht maar geen oplossing kunnen vinden. Als ik de gegevens onvoer krijg ik de melding Dat het eerste certificaat niet correct is.

Heb je enig idee wat ik nog kan doen?

Groetjes!

**Comment by marcschut002** [comment]
Hoi @wesllleyyy,

Krijg je deze melding alleen wanneer je connect met https?

Wanneer je verbinding maakt met https zal het certificaat geldig moeten zijn. 
Dit werkt enkel op basis van een hostname en niet op ipadres. (ik neem aan dat je deze combinatie gebruikt?)

Een oplossing kan dan zijn 
- om te connecten via http en een ipadres 
of 
- een hostname te gebruiken met certificaat
(https://www.synology.com/en-global/knowledgebase/DSM/tutorial/Network/How_to_enable_HTTPS_and_create_a_certificate_signing_request_on_your_Synology_NAS)

**Comment by wesllleyyy** [comment]
Hallo.

Nu je dat typt klinkt het eigenlijk wel logisch. Nu heb ik geprobeerd om het via http te doen met het lokale address en poort 5000(5001 krijg ik een unexepecter token in Jason error(volgensmij logisch is dan de https poort))  en dan gaat hij inderdaad zoeken maar hij blijft zoeken rondje blijft draaien doe ik nog iets fout?

Bedankt voor de snelle hulp!

Groetjes

**Comment by wesllleyyy** [comment]
Ow had een typ foutje het werkt hartelijk bedankt!
