### ISSUE TITLE
Homey White screen

### ISSUE THREAD

**Issue by Cultytpc** [martijnpoppen/com.synology.ss#4]
After installing this app, and adding a camera in favorites, my Homey app only shows White screen.. so now my Homey is useless unless i reset it completely.

I cannot remove the app either.

Can you help?

**Comment by marcschut002** [comment]
Hi @Cultytpc , I am not sure what this white screen means, but I will try to investigate. Do you have an iphone? Than you probably can kill the app ( https://support.apple.com/en-us/HT201330 ), start it again and you can delete this app.

**Comment by Cultytpc** [comment]
Hi,

It is suddenly working again.. i’ve tried everything, and gave up, and now the app works again, and i could remove the app. 

It was on iOS yes.

Thanks anyway

Mvh André Madsen

**Comment by marcschut002** [comment]
Strange thing, but I'm glad to hear that it's working again. I will close this issue for now, but please let me now if it happens again.
