### ISSUE TITLE
Is it possible to get the option to disable the certificates check?

### ISSUE THREAD

**Issue by Shakesbeard** [martijnpoppen/com.synology.ss#6]
Hi there,
So I wanted to connect Homey with the cameras over the local network directly. I'd rather like to avoid the "cloud detour". But for that to work I would need an option to ignore the certificates check as the certs used are only valid when the connection comes by fqdn in my case. That name however is not resolved locally because my router is not capable of such a feature.

So the connection seems to work but the login is rejected because the current certificate cannot be validated by Homey. Would it be possible to add an option in the pairing process to ignore cert failures?

**Comment by marcschut002** [comment]
Hi @Shakesbeard , The default setting for Homey is to validate these certificates. (secure by default). The reason there is no ignore option for this package is that it would mean that I would have to use 3rd party packages that make this app use more resources. 
The easiest way to solve this when you don't have a valid certificate is to use http iso https.

**Comment by Shakesbeard** [comment]
Solved. Missed to change the port for http.
