### ISSUE TITLE
Login probleem

### ISSUE THREAD

**Issue by Renevanhugten** [martijnpoppen/com.synology.ss#7]
Beste Marc,
Ik heb een inlog probleem wat doe ik fout?
Of moet ik nog iets instellen op de server van synology. 

![19A1E09D-482D-4A1D-A765-BC63267B0AC0](https://user-images.githubusercontent.com/29755580/80917765-71465400-8d61-11ea-85cd-5d1c92431bf8.jpeg)

Vriendelijke groet. 
Rene.

**Comment by marcschut002** [comment]
Hoi Rene,

Kan veel verschillende redenen zijn waarom je deze melding krijgt, maar gezien deze foutmelding weet Homey je wel het ipadres van je Synology te achterhalen. 
- De firewall op de Synology kan een issue zijn. Weet niet of je die aan hebt staan of specifiek heb ingesteld dat maar een enkel apparaat hier verbinding mee mag maken?
- Anders kan het te maken hebben met instellingen op de gebruiker zelf. Heeft de gebruiker die je hiervoor gebruikt wel de juiste rechten op de toepassing Surveillance Station?

**Comment by Renevanhugten** [comment]
Dank voor je snelle reactie.

Ik heb inderdaad de firewall even uit geschakeld, maar dat gaf geen resultaat.
Ik log in als Admin en gebruik de surveiliance app van synology al jaren en log met deze gegevens ook in. En als Admin log ik ook in op deze app.
Het enige wat ik zelf nog kan bedenken is dat er bijzondere karakters in mijn password zijn verwerkt. 

Tevens homey draait met versie 4.2.0 rc11

Dank alvast

Vriendelijke groet René van Hugten 

Verstuurd vanaf mijn iPad

**Comment by marcschut002** [comment]
Een wachtwoord met vreemde tekens kan ik me niet voorstellen, dan was het bij mij ook niet gelukt :-) . 

Ik heb de app nog niet getest met 4.2.0 rc11. Hierin zit wel een grote wijziging kwa nodejs versie, maar ik ben iets te afhankelijk van een degelijke Homey om te upgraden naar een rc versie, maar het zou wellicht kunnen.

Iets anders om nog uit te sluiten is MFA of 2FA op het account. Heb je die aanstaan?

**Comment by Renevanhugten** [comment]
Dank voor je berichtje,

Zat net even te testen met een ander password zonder vreemde tekens.
Dat gaf geen resultaat.  

Wat bedoel je precies met MFA en 2FA

2stap verificatie staat uit. 

Mvg rene 

Verstuurd vanaf mijn iPad

**Comment by marcschut002** [comment]
2FA = 2 stapsverificatie inderdaad.

Zou je eens willen testen via het lokale ip adres (+http en poort 5000) in plaats van de hostname?

**Comment by Renevanhugten** [comment]
Beste Marc,

Dit werkt perfect.
Ik hou de updates in de gaten voor de toekomst.
Dank voor je hulp en mooie app.
Met vriendelijke groet 
René van Hugten 


Verstuurd vanaf mijn iPad

**Comment by marcschut002** [comment]
@Renevanhugten dank voor jouw medewerking! 
Ik zal de nieuwe release ook zeker in de gaten houden om te voorkomen dat iedereen dit probleem gaat krijgen.
