### ISSUE TITLE
Camera does not supply video feed and motion detected

### ISSUE THREAD

**Issue by geurtd** [martijnpoppen/com.synology.ss#9]
Hi i have 3 cameras in my Surveillance Station
2 work fine, but one was added bit there is no video feed, also motion detection does not work on this one camera.
This is a Foscam FI9900EP.
A Foscam C1 and an Escam (installed as ONVIF) work fine.

**Comment by marcschut002** [comment]
Hi @geurtd , I am not sure why your third camera doesn't work with this app. Did you try to remove and add it again?
Do you have the correct license for Synology to support more than 2 camera's?

**Comment by geurtd** [comment]
Hi Marc,
Yes i did, and yes i have an extra licence. All 3 camera's function properly in surveillance station

**Comment by marcschut002** [comment]
I am not sure what the issue might be. I will try to add some debug info in the next release to figure this one out.

**Comment by geurtd** [comment]
Hello Marc,

 

Thanks for investigating.

 

Van: marcschut002 <notifications@github.com> 
Verzonden: zaterdag 12 december 2020 22:18
Aan: marcschut002/athom.com.synology.ss <athom.com.synology.ss@noreply.github.com>
CC: geurtd <geurt@geurt.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [marcschut002/athom.com.synology.ss] Camera does not supply video feed and motion detected (#9)

 

I am not sure what the issue might be. I will try to add some debug info in the next release to figure this one out.

**Comment by marcschut002** [comment]
Hi @geurtd , I have released a new test version (3.0.0). 
This version could solve your problem. 

https://homey.app/nl-nl/app/com.synology.ss/Surveillance-Station-2/test/ 

Would you like to test this release?
